TASK_NAME_MAX_LENGTH = 50
TASK_NAME_MIN_LENGTH = 1
LOCALHOST_PORT = 8000
LOCALHOST_NAME = '127.0.0.1'
LOCALHOST = f"http://{LOCALHOST_NAME}:{LOCALHOST_PORT}"
DEMO_USER_ID = 1
USER_NAME_MAX_LENGTH = 50
USER_NAME_MIN_LENGTH = 1
